version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend/scanner-app
    schedule:
      interval: weekly
      day: "sunday"
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
      day: "sunday"