version: 2
updates:
  - package-ecosystem: pip
    directory: "/backend"
    range: '>= {major}.{minor}, < {major+1}.0.0'
  - package-ecosystem: npm
    directory: "/frontend/checkout-app"
    range: '>= {major}.{minor}, < {major+1}.0.0'
  - package-ecosystem: npm
    directory: "/frontend/scanner-app"
    range: '>= {major}.{minor}, < {major+1}.0.0'

