exclude: "docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        entry: bash -c 'cd backend && mypy .'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        exclude: hooks/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        entry: bash -c 'cd backend && black .'

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        entry: bash -c 'cd backend && isort .'

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: bash -c 'cd backend && flake8 .'

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
