version: "3.9"

networks:
  backend:
    name: backend

x-common-variables: &postgres-common-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  db:
    image: postgres
    environment: *postgres-common-variables
    networks:
      - backend
    volumes:
      - ./backend/.docker-volumes/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: django_celery_worker
    command: "celery -A config:celery_app worker -l info"
    volumes:
      - .:/code/backend
    depends_on:
      - redis
      - db
      - web
    networks:
      - backend

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: socialpass-django-backend
    networks:
      - backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - 8000 # django server
      - 8888 # django shell_plus
    environment:
      <<: *postgres-common-variables
      CELERY_LOCAL_DEVELOPMENT: 'True'
      DJANGO_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  flower:
    image: mher/flower:0.9.7
    command: flower --broker=redis://redis:6379 --port=5555
    ports:
      - 5555:5555
    depends_on:
      - redis
    networks:
      - backend

  checkout-app:
    image: socialpass-checkout-app-app
    command: sh -c "yarn start --host"
    stdin_open: true
    volumes:
      - ./frontend/checkout-app/src/:/checkout-app/src/
      - ./frontend/checkout-app/package.json:/checkout-app/package.json
      - ./frontend/checkout-app/package-lock.json:/checkout-app/package-lock.json
    build:
      context: ./frontend/checkout-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  scanner-app:
    image: socialpass-scanner-app
    command: sh -c "yarn start --host"
    stdin_open: true
    volumes:
      - ./frontend/scanner-app/src/:/scanner/src/
      - ./frontend/scanner-app/package.json:/scanner/package.json
      - ./frontend/scanner-app/package-lock.json:/scanner/package-lock.json
    build:
      context: ./frontend/scanner-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
