[build]
  command = "apt-get update -y && apt-get install -y python3-dev libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev && pip install -r netlify-requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10.5"
  DJANGO_SETTINGS_MODULE = "config.settings.netlify"
  # Add this to prevent Python from writing bytecode files
  PYTHONDONTWRITEBYTECODE = "1"
  # Add this to configure Python to handle unbuffered output
  PYTHONUNBUFFERED = "1"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/django"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  framework = "django"
  command = "python manage.py runserver" 