# Generated by Django 3.2.11 on 2022-01-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0004_ticketgate_ticketlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Requirement",
        ),
    ]
