# Generated by Django 4.0.5 on 2022-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_datamigration_create_default_pricing_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='theme',
            field=models.JSONField(null=True),
        ),
    ]
