# Generated by Django 4.0.5 on 2022-07-08 22:01

import logging

from django.db import migrations


def create_default_pricing_group(apps, schema_editor):

    PricingRuleGroup = apps.get_model("dashboard", "PricingRuleGroup")
    PricingRule = apps.get_model("dashboard", "PricingRule")

    pricing_rule_group, created = PricingRuleGroup.objects.get_or_create(name="Default")
    # create pricing rules
    PricingRule.objects.create(
        min_capacity=1, max_capacity=999, price_per_ticket=1, group=pricing_rule_group
    )
    PricingRule.objects.create(
        min_capacity=1000,
        max_capacity=2999,
        price_per_ticket=0.75,
        group=pricing_rule_group,
    )
    PricingRule.objects.create(
        min_capacity=3000, price_per_ticket=0.5, group=pricing_rule_group
    )


def reverse_default_pricing_group(apps, schema_editor):
    PricingRuleGroup = apps.get_model("dashboard", "PricingRuleGroup")
    try:
        pricing_rule_group = PricingRuleGroup.objects.get(name="Default")
        pricing_rule_group.delete()
    except Exception:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_datamigration_create_default_pricing_group"),
    ]

    operations = [
        migrations.RunPython(
            create_default_pricing_group, reverse_code=reverse_default_pricing_group
        )
    ]
