# Generated by Django 4.0.5 on 2022-07-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_auto_20220708_2201"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventstripepayment",
            name="value_currency",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="eventstripepayment", name="value", field=models.IntegerField()
        ),
        migrations.AlterField(
            model_name="pricingrule",
            name="price_per_ticket",
            field=models.IntegerField(),
        ),
    ]
