# Generated by Django 4.0.5 on 2022-07-11 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0026_remove_event_custom_url_path_and_more"),
        ("dashboard", "0006_eventstripepayment_value_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventstripepayment",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="root.event",
            ),
        ),
    ]
