# Generated by Django 4.0.5 on 2022-07-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_team_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="theme",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
