# Generated by Django 4.0.6 on 2022-07-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0037_membership_pricingrulegroup_team_pricingrule_and_more"),
        ("dashboard", "0009_alter_team_theme"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="invite",
            name="inviter",
        ),
        migrations.RemoveField(
            model_name="invite",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="invite",
            name="team",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="membership",
            name="team",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="pricingrule",
            name="group",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.RemoveField(
            model_name="team",
            name="pricing_rule_group",
        ),
        migrations.DeleteModel(
            name="EventStripePayment",
        ),
        migrations.DeleteModel(
            name="Invite",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
        migrations.DeleteModel(
            name="PricingRule",
        ),
        migrations.DeleteModel(
            name="PricingRuleGroup",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
    database_operations = []

    # Note: We are reusing database in new table
    # No need to execute any operations
    migrations.SeparateDatabaseAndState(state_operations, database_operations)
