# Generated by Django 3.2.11 on 2022-02-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0011_softwareplan"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SoftwarePlan",
            new_name="Team",
        ),
    ]
