# Generated by Django 3.2.11 on 2022-02-10 14:39

from django.db import migrations
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0013_user_team"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", root.models.CustomUserManager()),
            ],
        ),
    ]
