# Generated by Django 3.2.11 on 2022-02-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0015_tokengate_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signature",
            name="id",
        ),
        migrations.AlterField(
            model_name="signature",
            name="unique_code",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
