# Generated by Django 3.2.11 on 2022-02-20 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20220220_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
