# Generated by Django 3.2.11 on 2022-02-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_tokengate_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokengate',
            name='public_id',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
