# Generated by Django 3.2.11 on 2022-02-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0024_alter_tokengate_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="signing_message",
            field=models.CharField(max_length=1024),
        ),
    ]
