# Generated by Django 3.2.11 on 2022-02-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_alter_signature_signing_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlist',
            name='token_id',
        ),
    ]
