# Generated by Django 3.2.11 on 2022-02-23 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_remove_ticketlist_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wallet_address', models.CharField(max_length=400)),
                ('transaction_hash', models.CharField(max_length=400)),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airdrops', to='root.signature')),
                ('tokengate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airdrops', to='root.airdropgate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wallet_address', models.CharField(max_length=400)),
                ('ticket_url', models.URLField()),
                ('signature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='root.signature')),
                ('tokengate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='root.ticketgate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ticketlist',
            name='tokengate',
        ),
        migrations.DeleteModel(
            name='AirdropList',
        ),
        migrations.DeleteModel(
            name='TicketList',
        ),
    ]
