# Generated by Django 3.2.11 on 2022-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0027_auto_20220223_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
