# Generated by Django 3.2.11 on 2022-03-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0030_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.team'),
        ),
    ]
