# Generated by Django 3.2.11 on 2022-03-08 20:06

import django.core.validators
from django.db import migrations, models
import root.validators


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_auto_20220303_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_url',
            new_name='download_url',
        ),
        migrations.RemoveField(
            model_name='airdropgate',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='ticketgate',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='ticketgate',
            name='requirements',
        ),
        migrations.AddField(
            model_name='tokengate',
            name='limit_per_person',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tokengate',
            name='requirements',
            field=models.JSONField(blank=True, default=list, null=True, validators=[root.validators.JSONSchemaValidator(limit_value={'items': {'anyOf': [{'properties': {'blockchain': {'enum': ['EVM']}}, 'required': ['chain_id', 'asset_type', 'asset_address']}], 'properties': {'amount': {'minimum': 1, 'type': 'integer'}, 'asset_address': {'pattern': '^(0x|0X).*$', 'type': 'string'}, 'asset_type': {'enum': ['ERC20', 'ERC721', 'ERC1155'], 'type': 'string'}, 'blockchain': {'enum': ['EVM'], 'type': 'string'}, 'chain_id': {'enum': ['1', '2', '4', '56', '43114', '137'], 'type': 'string'}, 'token_id': {'items': {'type': 'integer'}, 'minItems': 0, 'type': 'array'}}, 'required': ['blockchain', 'amount'], 'type': 'object'}, 'type': 'array'})]),
        ),
    ]
