# Generated by Django 3.2.11 on 2022-03-16 19:32

from django.db import migrations, models
import root.validators


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_auto_20220310_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='airdropgate',
            name='asset_type',
            field=models.CharField(choices=[('ERC20', 'ERC20'), ('ERC721', 'ERC721'), ('ERC1155', 'ERC1155')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tokengate',
            name='requirements',
            field=models.JSONField(blank=True, default=list, null=True, validators=[root.validators.JSONSchemaValidator(limit_value={'format': 'tabs', 'items': {'properties': {'amount': {'format': 'number', 'minimum': 1, 'title': 'Required Amount', 'type': 'integer'}, 'asset_address': {'pattern': '^(0x|0X).*$', 'title': 'Asset Address', 'type': 'string'}, 'asset_type': {'enum': ['ERC20', 'ERC721', 'ERC1155'], 'title': 'Asset Type', 'type': 'string'}, 'blockchain': {'enum': ['EVM'], 'title': 'Blockchain', 'type': 'string'}, 'chain_id': {'enum': [1, 2, 4, 56, 43114, 137], 'title': 'Network', 'type': 'integer'}, 'token_id': {'items': {'title': 'Token ID', 'type': 'integer'}, 'minItems': 0, 'title': 'Token IDs', 'type': 'array'}}, 'required': ['blockchain', 'asset_address', 'amount', 'chain_id', 'asset_type'], 'title': 'Requirement', 'type': 'object'}, 'properties': {}, 'title': 'Blockchain Requirements', 'type': 'array'})]),
        ),
    ]
