# Generated by Django 3.2.11 on 2022-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0037_auto_20220316_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketgate',
            name='timezone',
            field=models.CharField(max_length=30, null=True, verbose_name='time zone'),
        ),
    ]
