# Generated by Django 3.2.11 on 2022-03-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_ticketgate_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='subdomain',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
