# Generated by Django 3.2.11 on 2022-03-23 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0039_team_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='subdomain',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}', message='Subdomain should be FQDN')]),
        ),
    ]
