# Generated by Django 3.2.11 on 2022-03-23 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('root', '0041_alter_team_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokengate',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokengate',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_root.tokengate_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='team',
            name='subdomain',
            field=models.CharField(max_length=256, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', message='Subdomain only allows alphanumeric')]),
        ),
    ]
