# Generated by Django 3.2.11 on 2022-03-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0043_auto_20220328_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='download_url',
            new_name='image_url',
        ),
    ]
