# Generated by Django 3.2.11 on 2022-03-28 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0044_rename_download_url_ticket_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='filename',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
