# Generated by Django 3.2.11 on 2022-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0045_ticket_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
