# Generated by Django 3.2.11 on 2022-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0046_auto_20220328_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='temporary_download_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
