# Generated by Django 3.2.11 on 2022-03-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0047_ticket_temporary_download_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='temporary_download_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
