# Generated by Django 3.2.11 on 2022-04-05 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0049_auto_20220330_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokengate',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
