# Generated by Django 3.2.11 on 2022-04-12 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0050_alter_tokengate_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketgate',
            name='scanner_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
