# Generated by Django 3.2.11 on 2022-04-12 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0051_ticketgate_scanner_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='embed_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
