# Generated by Django 3.2.11 on 2022-04-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0052_ticket_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='embed_code',
            field=models.CharField(max_length=1024),
        ),
    ]
