# Generated by Django 3.2.11 on 2022-04-13 18:39

from django.db import migrations, models
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0053_alter_ticket_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='embed_code',
            field=models.CharField(default=root.models.Ticket.set_embed_code, max_length=1024),
        ),
        migrations.AlterField(
            model_name='ticketgate',
            name='scanner_code',
            field=models.CharField(default=root.models.TicketGate.set_scanner_code, max_length=1024),
        ),
    ]
