# Generated by Django 4.0.7 on 2022-10-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "root",
            "0007_rename_asset_ownership_checkoutsession_tx_asset_ownership_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("FIAT", "Fiat"),
                    ("BLOCKCHAIN", "Blockchain"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                ],
                default="FIAT",
                max_length=50,
            ),
        ),
    ]
