# Generated by Django 4.0.7 on 2022-10-16 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0008_checkoutsession_tx_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
    ]
