# Generated by Django 4.0.8 on 2022-10-18 01:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0012_remove_checkoutsession_status_remove_ticket_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierassetownership",
            name="asset_type",
            field=models.CharField(
                choices=[("NFT", "NFT")], default="NFT", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="tierassetownership",
            name="blockchain",
            field=models.CharField(
                choices=[("ETH", "Ethereum")], default="ETH", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="tierassetownership",
            name="network",
            field=models.CharField(
                choices=[
                    (1, "Ethereum"),
                    (5, "Ethereum (Goerli TestNet)"),
                    (11155111, "Ethereum (Sepolia TestNet)"),
                    (80001, "Ethereum (Mumbai TestNet)"),
                    (137, "Polygon"),
                    (56, "Binance Smart Chain"),
                    (97, "Binance Smart Chain (TestNet)"),
                    (43114, "Avalanche"),
                    (43113, "Avalanche (TestNet)"),
                    (250, "Fantom"),
                    (25, "Cronos"),
                    (338, "Cronos (TestNet)"),
                ],
                default=1,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tierassetownership",
            name="token_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="state",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("LIVE", "Live")],
                default="DRAFT",
                max_length=50
            ),
        ),
    ]
