# Generated by Django 4.0.8 on 2022-10-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0016_alter_event_cover_image_alter_event_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettier",
            name="price",
        ),
    ]
