# Generated by Django 4.0.8 on 2022-10-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0019_alter_tierassetownership_token_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                help_text="A banner image for your event.",
                upload_to="event__cover_image",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="team__image"),
        ),
    ]
