# Generated by Django 4.0.8 on 2022-11-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0024_checkoutsession_passcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierassetownership",
            name="balance_required",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="txassetownership",
            name="is_wallet_address_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="txassetownership",
            name="signed_message",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="txassetownership",
            name="wallet_address",
            field=models.CharField(default="", max_length=42),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="tx_asset_ownership",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="root.txassetownership",
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="tx_blockchain",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="root.txblockchain",
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="tx_fiat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="root.txfiat",
            ),
        ),
    ]
