# Generated by Django 4.0.8 on 2023-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0037_alter_tickettier_allowed_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierassetownership',
            name='network',
            field=models.IntegerField(choices=[(1, 'Ethereum'), (5, 'Ethereum (Goerli TestNet)'), (11155111, 'Ethereum (Sepolia TestNet)'), (80001, 'Ethereum (Mumbai TestNet)'), (137, 'Polygon'), (56, 'Binance Smart Chain'), (97, 'Binance Smart Chain (TestNet)'), (43114, 'Avalanche'), (43113, 'Avalanche (TestNet)'), (250, 'Fantom'), (25, 'Cronos'), (338, 'Cronos (TestNet)'), (42161, 'Arbitrum')], default=1),
        ),
    ]
