# Generated by Django 4.0.8 on 2023-03-29 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0039_ticket_party_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='party_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
