# Generated by Django 4.2 on 2023-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0043_tierfree_txfree_checkoutsession_tx_free_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("FIAT", "Fiat"),
                    ("BLOCKCHAIN", "Blockchain"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                    ("FREE", "Free"),
                ],
                default="FIAT",
                max_length=50,
            ),
        ),
    ]
