# Generated by Django 4.2 on 2023-05-11 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0046_txfree_error_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="txfree",
            name="error_message",
        ),
    ]
