# Generated by Django 4.2 on 2023-06-16 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0057_txfiat_stripe_line_items_txfiat_stripe_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="txfiat",
            name="stripe_line_items",
        ),
    ]
