# Generated by Django 4.2 on 2023-06-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0066_alter_tierassetownership_balance_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="A brand image for your team. Please make sure the image is square, non-transparent, and ideally in the PNG format.",
                null=True,
                upload_to="team__image",
            ),
        ),
    ]
