# Generated by Django 4.2.3 on 2023-08-29 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "root",
            "0075_rename_issued_emails_tierfree_deprecated_issued_emails_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="txassetownership",
            name="issued_token_id",
        ),
        migrations.AddField(
            model_name="txassetownership",
            name="redeemed_nfts",
            field=models.JSONField(default=list),
        ),
    ]
