# Generated by Django 4.2.6 on 2023-12-21 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0089_manualattendee"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_capacity",
            field=models.IntegerField(
                blank=True,
                help_text="Denotes the total capacity for the venue, across all ticket tiers.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="tickettier",
            name="guest_supply",
            field=models.IntegerField(
                blank=True,
                help_text="Denotes the total guest capacity.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
