# Generated by Django 4.2.6 on 2024-01-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0093_alter_checkoutsession_tx_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("FIAT", "Fiat"),
                    ("BLOCKCHAIN", "Blockchain"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                    ("FREE", "Free"),
                ],
                default="FIAT",
                max_length=50,
            ),
        ),
    ]
