# Generated by Django 5.0.1 on 2024-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0099_event_waiting_queue_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="skip_expiration",
            field=models.BooleanField(default=False),
        ),
    ]
