# Generated by Django 5.0.1 on 2024-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0101_rename_skip_expiration_checkoutsession_skip_validation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tickettier",
            options={"ordering": ("-modified",)},
        ),
        migrations.AddField(
            model_name="event",
            name="hide_address",
            field=models.BooleanField(default=False),
        ),
    ]
