# Generated by Django 5.0.2 on 2024-03-13 02:53

from django.db import migrations

def copy_data_from_tier_free(apps, schema_editor):
    TicketTier = apps.get_model('root', 'TicketTier')

    # Get and loop over all ticket tiers
    ticket_tiers = TicketTier.objects.all().select_related("tier_free")
    for tier in ticket_tiers:
        # Check for free relation
        # If none, skip to next item in loop
        if not tier.tier_free:
            continue

        # copy fields
        tier.deprecated_issued_emails = tier.tier_free.deprecated_issued_emails

        # save tier
        tier.save()

class Migration(migrations.Migration):

    dependencies = [
        ("root", "0119_tickettier_deprecated_issued_emails"),
    ]

    operations = [
        migrations.RunPython(
            copy_data_from_tier_free,
            reverse_code=migrations.RunPython.noop
        )
    ]
