# Generated by Django 5.0.2 on 2024-03-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0123_remove_tickettier_tier_asset_ownership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettier",
            name="tier_free",
        ),
        migrations.DeleteModel(
            name="TierFree",
        ),
    ]
