# Generated by Django 5.0.2 on 2024-03-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0130_remove_checkoutsession_tx_blockchain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="delegated_wallet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="is_wallet_address_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="redeemed_nfts",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="signed_message",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="wallet_address",
            field=models.CharField(default="", max_length=42),
        ),
    ]
