# Generated by Django 5.0.2 on 2024-03-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0133_migrate_checkoutsession_tx_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="tx_fiat",
        ),
        migrations.DeleteModel(
            name="TxFiat",
        ),
    ]
