# Generated by Django 5.0.2 on 2024-03-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0134_remove_checkoutsession_tx_fiat_delete_txfiat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="tx_free",
        ),
        migrations.DeleteModel(
            name="TxFree",
        ),
    ]
