# Generated by Django 5.0.2 on 2024-03-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0147_alter_checkoutsession_waitlist_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="signed_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, help_text="Stripe checkout session ID.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="stripe_session_url",
            field=models.TextField(
                blank=True, help_text="Stripe checkout session URL."
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="waitlist_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITLIST_JOINED", "Waitlist joined"),
                    ("WAITLIST_APPROVED", "Waitlist approved"),
                    ("WAITLIST_REJECTED", "Waitlist rejected"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="event",
            name="address_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="address_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="country",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(help_text="A short description of your event."),
        ),
        migrations.AlterField(
            model_name="event",
            name="geo_address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="geo_place_id",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="google_class_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="postal_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="event",
            name="region",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="event",
            name="timezone",
            field=models.CharField(blank=True, max_length=30, verbose_name="time zone"),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="stripe_account_country",
            field=models.CharField(
                blank=True, help_text="Connected Stripe account country.", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="stripe_account_id",
            field=models.CharField(
                blank=True, help_text="Connected Stripe account ID.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="tmp_stripe_account_id",
            field=models.CharField(
                blank=True,
                help_text="Temporary Stripe account ID used to create account links.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="google_class_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="additional_information",
            field=models.TextField(
                blank=True,
                help_text="Additional information for this tier provided by the host.",
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIAT", "Fiat"),
                    ("FREE", "Free"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="token_address",
            field=models.CharField(
                blank=True,
                help_text="What is the contract address of your NFT collection?",
                max_length=42,
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="css",
            field=models.TextField(blank=True),
        ),
    ]
