# Generated by Django 5.0.2 on 2024-03-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0156_rename_extra_party_checkoutitem_selected_guests_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="selected_guests",
            new_name="_selected_guests",
        ),
    ]
