# Generated by Django 5.0.2 on 2024-03-25 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0157_rename_selected_guests_ticket__selected_guests"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="selected_guests",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
