# Generated by Django 5.0.2 on 2024-03-25 03:06

from django.db import migrations


def migrate_selected_guests(apps, schema_editor):
    Ticket = apps.get_model('root', 'Ticket')

    # get all tickets
    tickets = Ticket.objects.all()
    for i in tickets:
        # copy _selected_guests -> selected_guests
        i.selected_guests = i._selected_guests
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0158_ticket_selected_guests"),
    ]

    operations = [
        migrations.RunPython(
            migrate_selected_guests,
            reverse_code=migrations.RunPython.noop
        )
    ]
