# Generated by Django 5.0.2 on 2024-03-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0160_remove_ticket__selected_guests"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManualAttendee",
        ),
    ]
