# Generated by Django 5.0.3 on 2024-03-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0162_alter_event_user_alter_tickettier_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettier",
            name="price_per_ticket_cents",
        ),
    ]
