# Generated by Django 5.0.3 on 2024-04-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0164_alter_tickettier_networks"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvpbatch",
            name="ticket_tier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="root.tickettier",
            ),
        ),
    ]
