# Generated by Django 5.0.3 on 2024-04-03 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0165_alter_event_description"),
        ("root", "0165_rsvpbatch_ticket_tier"),
    ]

    operations = []
