# Generated by Django 5.0.3 on 2024-04-09 19:25

from django.db import migrations

def migrate_rsvp_batch_strip_quotes(apps, schema_editor):
    RSVPBatch = apps.get_model('root', 'RSVPBatch')

    # Get all RSVP Batches, strip quotes
    rsvp_batches = RSVPBatch.objects.all()
    for batch in rsvp_batches:
        if batch.success_list:
            batch.success_list = [email.strip("'") for email in batch.success_list]
        if batch.failure_list:
            batch.failure_list = [email.strip("'") for email in batch.failure_list]
        batch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0169_alter_rsvpbatch_failure_list_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_rsvp_batch_strip_quotes,
            reverse_code=migrations.RunPython.noop
        )
    ]
