# Generated by Django 5.0.3 on 2024-04-25 07:00

import apps.root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0172_alter_team_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="A banner image for your event. Please make sure the image is a high quality landscape image, ideally 960 x 720 pixels (4:3).",
                null=True,
                upload_to="event__cover_image",
                validators=[apps.root.models.file_size],
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="A brand image for your team. Please make sure the image is square, non-transparent, and ideally in the PNG format.",
                null=True,
                upload_to="team__image",
                validators=[apps.root.models.file_size],
            ),
        ),
    ]
