# Generated by Django 5.0.3 on 2024-05-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0173_alter_event_cover_image_alter_team_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whitelabel",
            name="ticket_logo_apple",
        ),
        migrations.RemoveField(
            model_name="whitelabel",
            name="ticket_logo_google",
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="info_context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "red"),
                    ("sienna", "sienna"),
                    ("amber", "amber"),
                    ("yellow", "yellow"),
                    ("lime", "lime"),
                    ("green", "green"),
                    ("emerald", "emerald"),
                    ("turquoise", "turquoise"),
                    ("teal", "teal"),
                    ("cyan", "cyan"),
                    ("sky", "sky"),
                    ("blue", "blue"),
                    ("navy", "navy"),
                    ("indigo", "indigo"),
                    ("violet", "violet"),
                    ("purple", "purple"),
                    ("fuchsia", "fuchsia"),
                    ("pink", "pink"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="primary_context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "red"),
                    ("sienna", "sienna"),
                    ("amber", "amber"),
                    ("yellow", "yellow"),
                    ("lime", "lime"),
                    ("green", "green"),
                    ("emerald", "emerald"),
                    ("turquoise", "turquoise"),
                    ("teal", "teal"),
                    ("cyan", "cyan"),
                    ("sky", "sky"),
                    ("blue", "blue"),
                    ("navy", "navy"),
                    ("indigo", "indigo"),
                    ("violet", "violet"),
                    ("purple", "purple"),
                    ("fuchsia", "fuchsia"),
                    ("pink", "pink"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="brand_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="logo",
            field=models.ImageField(upload_to="whitelabel__logo"),
        ),
        migrations.AlterField(
            model_name="whitelabel",
            name="ticket_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="whitelabel__ticketlogo"
            ),
        ),
    ]
