# Generated by Django 4.0.7 on 2022-10-11 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0002_ticket_checkout_session_ticket_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutitem",
            name="checkout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.checkoutsession"
            ),
        ),
        migrations.AlterField(
            model_name="checkoutitem",
            name="ticket_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.tickettier"
            ),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.event"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="checkout_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.checkoutitem"
            ),
        ),
        migrations.AlterField(
            model_name="ticketredemptionkey",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.event"
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.event"
            ),
        ),
        migrations.AlterField(
            model_name="tickettierpaymenttype",
            name="ticket_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.tickettier"
            ),
        ),
        migrations.AlterField(
            model_name="txassetownership",
            name="checkout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.checkoutsession"
            ),
        ),
        migrations.AlterField(
            model_name="txblockchain",
            name="checkout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.checkoutsession"
            ),
        ),
        migrations.AlterField(
            model_name="txfiat",
            name="checkout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.checkoutsession"
            ),
        ),
    ]
