# Generated by Django 4.0.7 on 2022-10-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0006_tierassetownership_tierblockchain_tierfiat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkoutsession",
            old_name="asset_ownership",
            new_name="tx_asset_ownership",
        ),
        migrations.RenameField(
            model_name="checkoutsession",
            old_name="blockchain",
            new_name="tx_blockchain",
        ),
        migrations.RenameField(
            model_name="checkoutsession",
            old_name="fiat",
            new_name="tx_fiat",
        ),
        migrations.RenameField(
            model_name="tickettier",
            old_name="asset_ownership",
            new_name="tier_asset_ownership",
        ),
        migrations.RenameField(
            model_name="tickettier",
            old_name="blockchain",
            new_name="tier_blockchain",
        ),
        migrations.RenameField(
            model_name="tickettier",
            old_name="fiat",
            new_name="tier_fiat",
        ),
    ]
