# Generated by Django 4.0.7 on 2022-10-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0009_remove_event_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="filename",
        ),
    ]
