# Generated by Django 4.0.8 on 2022-10-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0010_remove_ticket_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettier",
            name="tier_asset_ownership",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="root.tierassetownership",
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="tier_blockchain",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="root.tierblockchain",
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="tier_fiat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="root.tierfiat",
            ),
        ),
    ]
