# Generated by Django 4.0.8 on 2022-10-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0013_tierassetownership_asset_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierassetownership",
            name="token_address",
            field=models.CharField(default="", max_length=42),
        ),
    ]
