# Generated by Django 4.0.8 on 2022-10-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0015_alter_tierassetownership_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                help_text="A banner image for your event.", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                default="", help_text="A short description of your event."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.CharField(
                default="",
                help_text="Name or brand or community organizing the event.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(help_text="When your event will start."),
        ),
        migrations.AlterField(
            model_name="event",
            name="timezone",
            field=models.CharField(default="", max_length=30, verbose_name="time zone"),
        ),
    ]
