# Generated by Django 4.0.8 on 2022-10-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_alter_event_cover_image_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(help_text='A brand image for your team. Please make sure the image is square, non-transparent, and ideally in the PNG format.', upload_to='team__image'),
        ),
    ]
