# Generated by Django 4.0.8 on 2022-11-08 02:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0025_tierassetownership_balance_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierassetownership",
            name="issued_token_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
    ]
