# Generated by Django 4.0.8 on 2023-01-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0034_event_is_featured_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
