# Generated by Django 4.0.8 on 2023-02-08 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_team_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='allowed_guests',
            field=models.IntegerField(default=0, help_text='Maximum number of guests allowed.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
