# Generated by Django 4.0.8 on 2023-02-08 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0036_tickettier_allowed_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='allowed_guests',
            field=models.IntegerField(default=0, help_text='Maximum number of guests allowed for one ticket.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
