# Generated by Django 4.2 on 2023-05-11 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0044_alter_checkoutsession_tx_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierfree",
            name="issued_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
