# Generated by Django 4.2 on 2023-05-24 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0047_remove_txfree_error_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="initial_place",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="event",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="event",
            name="long",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="archived",
        ),
    ]
