# Generated by Django 4.2 on 2023-06-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0049_remove_checkoutsession_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField()
        ),
    ]
