# Generated by Django 4.2 on 2023-06-01 00:16
from django.db import migrations
from django.utils.text import slugify

def populate_slug_field(apps, schema_editor):
    Event = apps.get_model('root', 'Event')  # Replace 'your_app_name' with your actual app name

    for event in Event.objects.all():
        if not event.slug and event.title:  # If the slug field is empty
            event.slug = slugify(event.title)
            event.save()

class Migration(migrations.Migration):
    dependencies = [
        ("root", "0050_event_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slug_field),
    ]
