# Generated by Django 4.2 on 2023-06-07 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0051_event_slug_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="fiat_currency",
            field=models.CharField(
                default="USD",
                help_text="The fiat currency to use for all tickets of this event.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tierfiat",
            name="price_per_ticket",
            field=models.DecimalField(
                decimal_places=2,
                default=0.99,
                help_text="Price of one ticket for this tier.",
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
