# Generated by Django 4.2 on 2023-06-07 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0052_event_fiat_currency_tierfiat_price_per_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tierfiat",
            name="price_per_ticket",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of one ticket for this tier.",
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
