# Generated by Django 4.2 on 2023-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0062_checkoutitem_is_overflow_alter_event_fiat_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name or brand or community organizing the event.",
                max_length=255,
            ),
        ),
    ]
