# Generated by Django 4.2 on 2023-06-26 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0063_alter_event_fiat_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="redeemed",
        ),
    ]
