# Generated by Django 4.2 on 2023-06-27 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0064_remove_ticket_redeemed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="redeemed_by",
        ),
        migrations.AddField(
            model_name="event",
            name="scanner_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name="TicketRedemptionKey",
        ),
    ]
