# Generated by Django 4.2.2 on 2023-07-05 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0065_remove_ticket_redeemed_by_event_scanner_id_and_more"),
        ("root", "0067_alter_team_image"),
    ]

    operations = []
