# Generated by Django 4.2.3 on 2023-08-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0071_rename_sales_end_date_event_sales_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettier",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not this tier is hidden from the public",
            ),
        ),
    ]
