# Generated by Django 4.2.3 on 2023-08-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0074_remove_txassetownership_error_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tierfree",
            old_name="issued_emails",
            new_name="deprecated_issued_emails",
        ),
        migrations.AddField(
            model_name="txfree",
            name="issued_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
