# Generated by Django 4.2.3 on 2023-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0077_whitelabel_team_whitelabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettier",
            name="additional_information",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional information for this tier provided by the host.",
            ),
        ),
    ]
