# Generated by Django 4.2.6 on 2023-10-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0080_rsvpbatch_checkoutsession_rsvp_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="is_waiting_list",
            field=models.BooleanField(default=False),
        ),
    ]
