# Generated by Django 4.2.6 on 2023-12-21 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0090_event_event_capacity_tickettier_guest_supply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_capacity",
            new_name="total_capacity",
        ),
    ]
