# Generated by Django 5.0.1 on 2024-02-15 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0103_invitation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invite",
        ),
    ]
