# Generated by Django 5.0.2 on 2024-02-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0105_tickettier_hidden_tickets_alter_event_fiat_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettier",
            name="hidden_tickets",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not this tickets available are hidden from public",
            ),
        ),
    ]
