# Generated by Django 5.0.2 on 2024-03-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0112_rename_ticket_type_tickettier_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickettier",
            old_name="tx_type",
            new_name="category",
        ),
    ]
