# Generated by Django 5.0.2 on 2024-03-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0125_remove_tickettier_tier_fiat_delete_tierfiat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="passcode_expiration",
        ),
    ]
