# Generated by Django 5.0.2 on 2024-03-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0126_remove_checkoutsession_passcode_expiration"),
        ("root", "0126_event_geo_address_event_geo_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="cost",
        ),
    ]
