# Generated by Django 5.0.2 on 2024-03-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0127_remove_checkoutsession_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="stripe_line_items",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe checkout session ID.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="stripe_session_url",
            field=models.TextField(
                blank=True, default="", help_text="Stripe checkout session URL."
            ),
        ),
    ]
