# Generated by Django 5.0.2 on 2024-03-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0129_migrate_tx_fiat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="tx_blockchain",
        ),
        migrations.DeleteModel(
            name="TxBlockchain",
        ),
    ]
