# Generated by Django 5.0.2 on 2024-03-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0136_remove_checkoutsession_tx_asset_ownership_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkoutsession",
            old_name="tx_type",
            new_name="session_type",
        ),
    ]
