# Generated by Django 5.0.2 on 2024-03-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0137_rename_tx_type_checkoutsession_session_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkoutsession",
            old_name="tx_status",
            new_name="order_status",
        ),
    ]
