# Generated by Django 5.0.2 on 2024-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0138_rename_tx_status_checkoutsession_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="waitlist_status",
            field=models.CharField(
                choices=[
                    ("WAITLIST_JOINED", "Waitlist joined"),
                    ("WAITLIST_APPROVED", "Waitlist approved"),
                    ("WAITLIST_REJECTED", "Waitlist approved"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
