# Generated by Django 5.0.2 on 2024-03-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0145_alter_checkoutsession_waitlist_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("FIAT", "Fiat"),
                    ("FREE", "Free"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                ],
                default="FIAT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIAT", "Fiat"),
                    ("FREE", "Free"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
