# Generated by Django 5.0.2 on 2024-03-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0148_alter_checkoutsession_signed_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="state",
        ),
    ]
