# Generated by Django 5.0.2 on 2024-03-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0149_remove_event_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_featured_top",
        ),
    ]
