# Generated by Django 5.0.2 on 2024-03-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0150_remove_event_is_featured_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="fiat_currency",
            field=models.CharField(
                default="USD",
                help_text="The fiat currency to use for all tickets of this event.",
                max_length=3,
            ),
        ),
    ]
