# Generated by Django 5.0.2 on 2024-03-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0152_auto_20240322_0250"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="address_1",
        ),
        migrations.RemoveField(
            model_name="event",
            name="address_2",
        ),
        migrations.RemoveField(
            model_name="event",
            name="city",
        ),
        migrations.RemoveField(
            model_name="event",
            name="country",
        ),
        migrations.RemoveField(
            model_name="event",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="event",
            name="region",
        ),
    ]
