# Generated by Django 5.0.2 on 2024-03-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0154_remove_team_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickettier",
            old_name="allowed_guests",
            new_name="guests_allowed",
        ),
    ]
