# Generated by Django 5.0.2 on 2024-03-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0155_rename_allowed_guests_tickettier_guests_allowed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkoutitem",
            old_name="extra_party",
            new_name="selected_guests",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="extra_party",
            new_name="selected_guests",
        ),
    ]
