# Generated by Django 5.0.2 on 2024-03-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0159_auto_20240325_0306"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="_selected_guests",
        ),
    ]
