# Generated by Django 5.0.1 on 2024-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0164_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(help_text="A short description of your event."),
        ),
    ]
