# Generated by Django 5.0.3 on 2024-04-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0171_alter_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
