# Generated by Django 4.0.4 on 2022-06-16 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    database_operations = [
        migrations.AlterModelTable("Invite", "dashboard_invite"),
        migrations.AlterModelTable("Membership", "dashboard_membership"),
    ]

    state_operations = [
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="membership",
            name="team",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                through="dashboard.Membership", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Invite",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
