# Generated by Django 4.0.7 on 2022-10-11 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checkout_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="root.checkoutsession",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="root.event"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_tier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="root.tickettier",
            ),
        ),
        migrations.AlterField(
            model_name="txassetownership",
            name="checkout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_ownership_transactions",
                to="root.checkoutsession",
            ),
        ),
    ]
