# Generated by Django 4.0.4 on 2022-05-18 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='signing_message',
        ),
        migrations.AddField(
            model_name='invite',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.membership'),
        ),
    ]
