# Generated by Django 4.0.7 on 2022-10-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txassetownership',
            name='checkout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_ownership_transactions', to='root.checkoutsession'),
        ),
    ]
