# Generated by Django 4.0.4 on 2022-05-27 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_remove_signature_signing_message_invite_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RedemptionAccessKey',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticketed_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_access_keys', to='root.ticketedevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='redeemed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.redemptionaccesskey'),
        ),
    ]
