# Generated by Django 4.0.4 on 2022-04-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_signature_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asset_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
