# Generated by Django 4.0.4 on 2022-05-23 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_remove_signature_signing_message_invite_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticketedeventstripepayment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
