# Generated by Django 4.0.4 on 2022-06-16 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0002_alter_membership_unique_together_and_more"),
    ]

    database_operations = [
        migrations.AlterModelTable("EventStripePayment", "dashboard_eventstripepayment"),
        migrations.AlterModelTable("PricingRule", "dashboard_pricingrule"),
        migrations.AlterModelTable("PricingRuleGroup", "dashboard_pricingrulegroup"),
        migrations.AlterModelTable("Team", "dashboard_team"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="pricingrule",
            name="group",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.RemoveField(
            model_name="team",
            name="pricing_rule_group",
        ),
        migrations.AlterField(
            model_name="event",
            name="pricing_rule",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="dashboard.pricingrule",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="team",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.team",
            ),
        ),
        migrations.DeleteModel(
            name="EventStripePayment",
        ),
        migrations.DeleteModel(
            name="PricingRule",
        ),
        migrations.DeleteModel(
            name="PricingRuleGroup",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(database_operations=database_operations, state_operations=state_operations)
    ]
