# Generated by Django 4.0.4 on 2022-06-07 23:24
import logging
from django.db import migrations


def create_default_pricing_group(apps, schema_editor):

    PricingRuleGroup = apps.get_model("root", "PricingRuleGroup")

    pricing_rule_group, created = PricingRuleGroup.objects.get_or_create(name="Default")
    if created:
        pricing_rule_group.description = "Default pricing rule group"
        pricing_rule_group.save()

    if PricingRuleGroup.objects.count() > 1:
        logging.warning(
            "PricingRuleGroup already exists in database. Default still created. Maybe as a result there are two default pricing rule groups. Please check the database"
        )  # noqa


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0002_pricingrulegroup_description"),
    ]

    operations = [migrations.RunPython(create_default_pricing_group)]
