# Generated by Django 4.0.7 on 2022-10-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0003_alter_checkoutitem_checkout_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="show_team_image",
        ),
        migrations.RemoveField(
            model_name="event",
            name="show_ticket_count",
        ),
        migrations.RemoveField(
            model_name="event",
            name="visibility",
        ),
    ]
