# Generated by Django 4.0.4 on 2022-05-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_pricingrule_price_per_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='ticketedevent',
            name='scanner_code',
        ),
    ]
