# Generated by Django 4.0.4 on 2022-05-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_ticket_redeemed_by'),
        ('root', '0004_remove_team_subdomain_and_more'),
    ]

    operations = [
    ]
