# Generated by Django 4.0.4 on 2022-04-25 16:33

import apps.root.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_ticket_asset_address_remove_ticket_token_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='option',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requirement',
            field=models.JSONField(blank=True, null=True, validators=[apps.root.validators.JSONSchemaValidator(limit_value={'format': 'tabs', 'properties': {'properties': {'amount': {'format': 'number', 'minimum': 1, 'title': 'Required Amount', 'type': 'integer'}, 'asset_address': {'pattern': '^(0x|0X).*$', 'title': 'Asset Address', 'type': 'string'}, 'asset_type': {'enum': ['ERC20', 'ERC721', 'ERC1155'], 'title': 'Asset Type', 'type': 'string'}, 'blockchain': {'enum': ['EVM'], 'title': 'Blockchain', 'type': 'string'}, 'chain_id': {'enum': [1, 2, 4, 56, 43114, 137], 'title': 'Network', 'type': 'integer'}, 'to_block': {'format': 'number', 'minimum': 1, 'title': 'Snapshot block (for fungible tokens)', 'type': 'integer'}, 'token_id': {'items': {'title': 'Token ID', 'type': 'integer'}, 'minItems': 0, 'title': 'Token IDs', 'type': 'array'}}, 'required': ['blockchain', 'asset_address', 'amount', 'chain_id', 'asset_type'], 'title': 'Requirement', 'type': 'object'}, 'title': 'Blockchain Requirements', 'type': 'object'})]),
        ),
    ]
