# Generated by Django 4.0.7 on 2022-10-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0004_remove_event_publication_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="checkout_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.checkoutsession"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.event"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.tickettier"
            ),
        ),
    ]
