# Generated by Django 4.0.4 on 2022-05-26 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_team_subdomain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='embed_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
