# Generated by Django 4.0.4 on 2022-05-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_team_subdomain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='temporary_download_url',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='wallet_address',
        ),
    ]
