# Generated by Django 4.0.4 on 2022-05-14 04:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_ticket_option_alter_ticket_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('min_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_capacity', models.IntegerField(null=True)),
                ('price_per_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.pricingrulegroup')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='pricing_rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.pricingrulegroup'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(check=models.Q(('max_capacity__isnull', True), ('max_capacity__gt', django.db.models.expressions.F('min_capacity')), _connector='OR'), name='root_pricingrule_max_capacity__gt__min_capacity'),
        ),
    ]
