# Generated by Django 4.0.4 on 2022-05-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_invitation_id'),
        ('root', '0005_ticket_option_alter_ticket_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invitation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invitations.invitation')),
                ('archived_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.team')),
            ],
            options={
                'abstract': False,
            },
            bases=('invitations.invitation',),
        ),
    ]
