# Generated by Django 4.0.4 on 2022-05-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_merge_20220527_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='temporary_download_url',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='wallet_address',
        ),
    ]
