# Generated by Django 4.0.5 on 2022-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0006_remove_event_location_event_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
