# Generated by Django 4.0.4 on 2022-05-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_pricingrulegroup_pricingrule_team_pricing_rules_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='pricing_rules',
            new_name='pricing_rule_group',
        ),
    ]
