# Generated by Django 4.0.4 on 2022-06-16 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0006_remove_pricingrule_group_remove_team_members_and_more"),
    ]

    operations = [
        migrations.RenameModel("RedemptionAccessKey", "TicketRedemptionKey"),
        migrations.AlterField(
            model_name="ticket",
            name="redeemed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="root.ticketredemptionkey",
            ),
        ),
        migrations.AlterField(
            model_name="ticketredemptionkey",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_redemption_keys",
                to="root.event",
            ),
        ),
    ]
