# Generated by Django 4.0.4 on 2022-05-31 04:13

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_remove_ticket_image_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='option',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='requirement',
        ),
    ]
