# Generated by Django 4.0.4 on 2022-06-01 02:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_user_managers_remove_ticket_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CANCELLED', 'Cancelled'), ('SUCCESS', 'Succeeded'), ('FAILURE', 'Failed')], default='PENDING', max_length=30)),
                ('stripe_checkout_session_id', models.CharField(max_length=1024)),
                ('callaback_timestamp', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='redemptionaccesskey',
            old_name='ticketed_event',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='signature',
            old_name='ticketed_event',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketed_event',
            new_name='event',
        ),
        migrations.RenameModel(
            old_name='TicketedEvent',
            new_name='Event',
        ),
        migrations.DeleteModel(
            name='TicketedEventStripePayment',
        ),
        migrations.AddField(
            model_name='eventstripepayment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='root.event'),
        ),
    ]
