# Generated by Django 4.0.4 on 2022-05-14 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_rename_pricing_rules_team_pricing_rule_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketgate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ticketgate',
            name='pricing_rule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='root.pricingrule'),
        ),
    ]
