# Generated by Django 4.0.5 on 2022-06-24 01:09
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0007_rename_date_event_start_date_event_end_date"),
    ]

    operations = [
        CreateExtension("postgis"),
    ]
