# Generated by Django 4.0.4 on 2022-06-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0007_ticketredemptionkey_alter_ticket_redeemed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="featured",
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
