# Generated by Django 4.0.4 on 2022-05-14 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_pricingrule_active_ticketgate_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='pricing_rule_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.pricingrulegroup'),
        ),
        migrations.AlterField(
            model_name='ticketgate',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticketgate',
            name='pricing_rule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='root.pricingrule'),
        ),
    ]
