# Generated by Django 4.0.4 on 2022-06-01 17:34

import apps.root.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_eventstripepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainOwnership',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=400)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(default=apps.root.models.BlockchainOwnership.set_expires)),
                ('version', models.IntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='signature',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
        migrations.AddField(
            model_name='ticket',
            name='blockchain_ownership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='root.blockchainownership'),
        ),
    ]
