# Generated by Django 4.0.4 on 2022-06-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_blockchainownership_remove_ticket_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='blockchain_asset',
            field=models.JSONField(null=True),
        ),
    ]
