# Generated by Django 4.0.5 on 2022-06-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0009_event_custom_url_path_event_organizer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
