# Generated by Django 4.0.4 on 2022-05-14 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_alter_pricingrule_max_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingrule',
            old_name='price_per_capacity',
            new_name='price_per_ticket',
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='root.pricingrulegroup'),
        ),
        migrations.CreateModel(
            name='TokenGatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('token_gate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='root.tokengate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
