# Generated by Django 4.0.4 on 2022-05-15 18:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_rename_price_per_capacity_pricingrule_price_per_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenGateStripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('CANCELLED', 'CANCELLED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=30)),
                ('stipe_checkout_session_id', models.CharField(max_length=1024)),
                ('callaback_timestamp', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_timestamp', models.DateTimeField(blank=True, null=True)),
                ('token_gate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='root.tokengate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TokenGatePayment',
        ),
    ]
