# Generated by Django 4.0.4 on 2022-06-02 01:41

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_ticket_blockchain_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, storage=config.storages.PrivateTicketStorage(), upload_to=''),
        ),
    ]
