# Generated by Django 4.0.5 on 2022-06-26 16:25

import taggit.managers
from django.db import migrations, models

import config.storages


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("root", "0010_event_is_draft_alter_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="categories",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.MediaRootS3Boto3Storage(),
                upload_to="",
            ),
        ),
    ]
