# Generated by Django 4.0.8 on 2022-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0011_alter_tickettier_tier_asset_ownership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="status",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="file",
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="tx_status",
            field=models.CharField(
                choices=[
                    ("VALID", "Valid"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                    ("COMPLETED", "Completed"),
                ],
                default="VALID",
                max_length=50,
            ),
        ),
    ]
