# Generated by Django 4.0.4 on 2022-06-02 13:52

import apps.root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='image',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='blockchainownership',
            name='version',
        ),
        migrations.AddField(
            model_name='blockchainownership',
            name='expires',
            field=models.DateTimeField(default=apps.root.models.BlockchainOwnership.set_expires),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
