# Generated by Django 4.0.4 on 2022-05-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_tokengatestripepayment_delete_tokengatepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokengatestripepayment',
            old_name='stipe_checkout_session_id',
            new_name='stripe_checkout_session_id',
        ),
    ]
