# Generated by Django 4.0.5 on 2022-06-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0011_alter_event_categories_alter_event_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
