# Generated by Django 4.0.4 on 2022-05-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_invite'),
        ('root', '0012_rename_stipe_checkout_session_id_tokengatestripepayment_stripe_checkout_session_id'),
    ]

    operations = [
    ]
