# Generated by Django 4.0.4 on 2022-06-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_rename_image_ticket_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionaccesskey',
            name='name',
            field=models.CharField(default='Default', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='redemptionaccesskey',
            unique_together={('event', 'name')},
        ),
    ]
