# Generated by Django 4.0.5 on 2022-06-27 02:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0013_alter_event_capacity_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="file",
            field=models.ImageField(
                null=True,
                storage=django.core.files.storage.FileSystemStorage,
                upload_to="",
            ),
        ),
    ]
