# Generated by Django 4.0.4 on 2022-06-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_redemptionaccesskey_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrulegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
