# Generated by Django 4.0.4 on 2022-05-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_merge_20220517_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokengatestripepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CANCELLED', 'Cancelled'), ('SUCCESS', 'Succeeded'), ('FAILURE', 'Failed')], default='PENDING', max_length=30),
        ),
    ]
