# Generated by Django 4.0.5 on 2022-06-27 14:57

from django.db import migrations, models

import config.storages


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0014_alter_ticket_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="file",
            field=models.ImageField(
                null=True, storage=config.storages.PrivateTicketStorage(), upload_to=""
            ),
        ),
    ]
