# Generated by Django 4.0.5 on 2022-06-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0014_alter_event_capacity_alter_event_description"),
        ("root", "0015_alter_ticket_file"),
    ]

    operations = []
