# Generated by Django 4.0.5 on 2022-06-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0015_alter_ticket_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
