# Generated by Django 4.0.4 on 2022-06-07 23:55

import apps.root.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_datamigration_create_default_pricing_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pricing_rule_group',
            field=models.ForeignKey(default=apps.root.models.Team.get_default_pricing_rule_group, on_delete=django.db.models.deletion.CASCADE, to='root.pricingrulegroup'),
        ),
    ]
