# Generated by Django 4.0.5 on 2022-06-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0016_merge_20220628_2046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="publish_date",
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
