# Generated by Django 4.0.5 on 2022-06-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0016_event_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
