# Generated by Django 4.0.5 on 2022-06-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0017_remove_event_publish_date_alter_event_location"),
        ("root", "0017_alter_event_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
