# Generated by Django 4.0.8 on 2022-10-19 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_alter_tickettier_tier_asset_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tierassetownership',
            name='token_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Please enter a list of token ID(s) separated by commas.', null=True, size=None),
        ),
    ]
