# Generated by Django 4.0.5 on 2022-07-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0020_rename_categories_event_tags_remove_event_timezone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timezone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="time zone"
            ),
        ),
    ]
