# Generated by Django 4.0.8 on 2022-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_alter_event_address_1_alter_event_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
