# Generated by Django 4.0.8 on 2022-10-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_alter_event_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(help_text='A banner image for your event. Please make sure the image is a high quality landscape image, ideally 960 x 720 pixels (4:3).', upload_to='event__cover_image'),
        ),
    ]
