# Generated by Django 4.0.5 on 2022-07-09 00:09

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0022_remove_event_is_draft_alter_event_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="state",
            field=django_fsm.FSMField(default="Draft", max_length=50, protected=True),
        ),
    ]
