# Generated by Django 4.0.5 on 2022-07-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0023_event_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price_currency",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event", name="price", field=models.IntegerField()
        ),
    ]
