# Generated by Django 4.0.8 on 2022-11-03 19:11

import apps.root.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_alter_event_address_1_alter_event_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='passcode',
            field=models.CharField(default=apps.root.models.get_random_passcode, max_length=6),
        ),
    ]
