# Generated by Django 4.0.5 on 2022-07-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0024_event_price_currency_alter_event_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="price",
            new_name="_price",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="price_currency",
            new_name="_price_currency",
        ),
    ]
