# Generated by Django 4.0.5 on 2022-07-10 04:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0025_rename_price_event__price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="custom_url_path",
        ),
        migrations.AlterField(
            model_name="event",
            name="publish_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
