# Generated by Django 4.0.5 on 2022-07-11 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0026_remove_event_custom_url_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="publish_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
