# Generated by Django 4.0.5 on 2022-07-11 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_eventstripepayment_event"),
        ("root", "0027_alter_event_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.team"
            ),
        ),
    ]
