# Generated by Django 4.0.8 on 2022-11-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0028_alter_tierassetownership_issued_token_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="localized_address_display",
        ),
    ]
