# Generated by Django 4.0.5 on 2022-07-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0028_alter_event_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=50,
            ),
        ),
    ]
