# Generated by Django 4.0.5 on 2022-07-15 20:31

from django.db import migrations, models

import config.storages


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0029_alter_event_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="file",
            field=models.ImageField(
                null=True,
                storage=config.storages.get_private_ticket_storage,
                upload_to="",
            ),
        ),
    ]
