# Generated by Django 4.0.8 on 2022-11-23 13:41

from django.db import migrations, models

import apps.root.models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0029_remove_event_localized_address_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="expiration",
            field=models.DateTimeField(
                blank=True, default=apps.root.models.get_expiration_datetime, null=True
            ),
        ),
    ]
