# Generated by Django 4.0.5 on 2022-07-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0030_alter_event_cover_image_alter_ticket_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="timezone_offset",
        ),
    ]
