# Generated by Django 4.0.8 on 2022-12-01 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0030_alter_checkoutsession_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="txassetownership",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="txassetownership",
            name="token_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
