# Generated by Django 4.0.5 on 2022-07-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0031_remove_event_timezone_offset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventLocation",
        ),
        migrations.AddField(
            model_name="event",
            name="address_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="address_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="long",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="postal_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="region",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
