# Generated by Django 4.0.8 on 2022-12-13 10:44

import apps.root.models
from django.db import migrations, models

def get_expiration_datetime():
    """
    Get current datetime + 10 minutes
    """
    return timezone.now() + timezone.timedelta(hours=24)

class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_txassetownership_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='passcode_expiration',
            field=models.DateTimeField(default=get_expiration_datetime),
        ),
    ]
