# Generated by Django 4.0.5 on 2022-07-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0032_delete_eventlocation_event_address_1_event_address_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="postal_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="region",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
