# Generated by Django 4.0.8 on 2022-12-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_checkoutsession_passcode_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail address'),
        ),
    ]
