# Generated by Django 4.0.8 on 2023-01-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_alter_invite_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured_top',
            field=models.BooleanField(default=False),
        ),
    ]
