# Generated by Django 4.0.8 on 2023-01-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_alter_invite_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Brief name for your event. Must be unique!', max_length=255),
        ),
    ]
