# Generated by Django 4.0.5 on 2022-07-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0033_alter_event_postal_code_alter_event_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="localized_address_display",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
