# Generated by Django 4.0.5 on 2022-07-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0034_event_localized_address_display"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="publish_date",
            new_name="publication_date",
        ),
    ]
