# Generated by Django 4.0.5 on 2022-07-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0035_rename_publish_date_event_publication_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="show_team_image",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="show_ticket_count",
            field=models.BooleanField(default=True),
        ),
    ]
