# Generated by Django 4.0.8 on 2023-02-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0035_team_is_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickettier",
            old_name="max_per_person",
            new_name="max_per_order",
        ),
    ]
