# Generated by Django 4.0.8 on 2023-02-07 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0036_rename_max_per_person_tickettier_max_per_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettier",
            name="capacity",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Maximum amount of attendees for this ticket tier, including guests.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="max_per_order",
            field=models.IntegerField(
                default=1,
                help_text="Maximum amount of tickets per order.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
