# Generated by Django 4.0.6 on 2022-07-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0037_membership_pricingrulegroup_team_pricingrule_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="eventstripepayment",
            table="root_eventstripepayment",
        ),
        migrations.AlterModelTable(
            name="invite",
            table="root_invite",
        ),
        migrations.AlterModelTable(
            name="membership",
            table="root_membership",
        ),
        migrations.AlterModelTable(
            name="pricingrule",
            table="root_pricingrule",
        ),
        migrations.AlterModelTable(
            name="pricingrulegroup",
            table="root_pricingrulegroup",
        ),
        migrations.AlterModelTable(
            name="team",
            table="root_team",
        ),
    ]
