# Generated by Django 4.0.8 on 2023-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0037_alter_tickettier_allowed_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='is_guest_tier',
            field=models.BooleanField(default=False),
        ),
    ]
