# Generated by Django 4.0.8 on 2023-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0037_alter_tickettier_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettier",
            name="allowed_guests",
            field=models.IntegerField(
                default=1,
                help_text="Number of complentary guest tickets an attendee will receive",
            ),
        ),
    ]
