# Generated by Django 4.0.8 on 2023-02-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_tickettier_is_guest_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettier',
            name='allowed_guests',
        ),
    ]
