# Generated by Django 4.0.8 on 2023-02-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0038_tickettier_allowed_guests"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
