# Generated by Django 4.0.6 on 2022-07-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0038_alter_eventstripepayment_table_alter_invite_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="eventstripepayment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="invite",
            table=None,
        ),
        migrations.AlterModelTable(
            name="membership",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pricingrule",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pricingrulegroup",
            table=None,
        ),
        migrations.AlterModelTable(
            name="team",
            table=None,
        ),
    ]
