# Generated by Django 4.0.8 on 2023-03-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0038_alter_tierassetownership_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="party_size",
            field=models.IntegerField(default=1),
        ),
    ]
