# Generated by Django 4.0.6 on 2022-07-28 23:34

import sorl.thumbnail.fields
from django.db import migrations

import config.storages


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0042_alter_event_capacity_alter_event_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                help_text="A banner image for your event.",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, max_length=255, null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="file",
            field=sorl.thumbnail.fields.ImageField(
                null=True,
                storage=config.storages.get_private_ticket_storage,
                upload_to="",
            ),
        ),
    ]
