# Generated by Django 4.0.6 on 2022-08-29 02:05

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0043_rename_location_event_initial_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.UUIDField(null=True)),
                ("wallet_address", models.CharField(max_length=400)),
                ("is_verified", models.BooleanField(default=False)),
                ("expires", models.DateTimeField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.event"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="blockchain_asset",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="blockchain_ownership",
        ),
        migrations.DeleteModel(
            name="BlockchainOwnership",
        ),
    ]
