# Generated by Django 4.0.7 on 2022-09-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0043_rename_location_event_initial_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingrule",
            name="group",
        ),
        migrations.RemoveField(
            model_name="event",
            name="_price",
        ),
        migrations.RemoveField(
            model_name="event",
            name="_price_currency",
        ),
        migrations.RemoveField(
            model_name="event",
            name="pricing_rule",
        ),
        migrations.RemoveField(
            model_name="team",
            name="pricing_rule_group",
        ),
        migrations.DeleteModel(
            name="EventStripePayment",
        ),
        migrations.DeleteModel(
            name="PricingRule",
        ),
        migrations.DeleteModel(
            name="PricingRuleGroup",
        ),
    ]
