# Generated by Django 4.0.7 on 2022-09-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0043_rename_location_event_initial_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="google_class_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="google_class_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
