# Generated by Django 4.0.7 on 2022-09-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0044_remove_pricingrule_group_remove_event__price_and_more"),
        ("root", "0044_event_google_class_id_ticket_google_class_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.DeleteModel(
            name="EventCategory",
        ),
    ]
