# Generated by Django 4.0.6 on 2022-08-29 03:54

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0044_attendee_remove_ticket_blockchain_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="requirements",
        ),
        migrations.CreateModel(
            name="Requirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("asset_address", models.CharField(max_length=1024)),
                (
                    "blockchain",
                    models.CharField(
                        choices=[("EVM", "Evm")], default="EVM", max_length=12
                    ),
                ),
                (
                    "chain_id",
                    models.CharField(
                        choices=[
                            ("1", "Ethereum"),
                            ("2", "Ropsten"),
                            ("4", "Rinkeby"),
                            ("56", "BNB Chain"),
                            ("43114", "Avalanche"),
                            ("137", "Polygon"),
                        ],
                        default="1",
                        max_length=12,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("ERC20", "Erc20"),
                            ("ERC721", "Erc721"),
                            ("ERC1155", "Erc1155"),
                        ],
                        default="ERC20",
                        max_length=12,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements",
                        to="root.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
