# Generated by Django 4.0.7 on 2022-09-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0045_remove_event_category_delete_eventcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="address_1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="address_2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="country",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="A short description of your event."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="google_class_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="initial_place",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Where your event will take place.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="localized_address_display",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name or brand or community organizing the event.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="event",
            name="region",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="event",
            name="timezone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="time zone"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="google_class_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
