# Generated by Django 4.0.6 on 2022-08-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0045_remove_event_requirements_requirements"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Requirements",
            new_name="BlockchainRequirements",
        ),
    ]
