# Generated by Django 4.2 on 2023-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0045_tierfree_issued_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="txfree",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
