# Generated by Django 4.0.6 on 2022-08-29 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0046_rename_requirements_blockchainrequirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainrequirements",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="root.event"
            ),
        ),
    ]
