# Generated by Django 4.0.6 on 2022-08-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0047_alter_blockchainrequirements_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.DeleteModel(
            name="EventCategory",
        ),
    ]
