# Generated by Django 4.2 on 2023-05-30 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0048_remove_event_initial_place_remove_event_is_featured_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="expiration",
        ),
    ]
