# Generated by Django 4.0.7 on 2022-09-06 02:21

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0048_remove_event_category_delete_eventcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(default="Default", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("Asset Ownership", "Asset Ownership")],
                        default="Asset Ownership",
                        max_length=36,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="Maximum amount of attendees for this ticket type.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_quantity",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum amount of tickets for this ticket type.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_quantity",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum amount of tickets for this ticket type.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("asset_address", models.CharField(max_length=1024)),
                (
                    "blockchain",
                    models.CharField(
                        choices=[("EVM", "Evm")], default="EVM", max_length=12
                    ),
                ),
                (
                    "chain_id",
                    models.CharField(
                        choices=[
                            ("1", "Ethereum"),
                            ("2", "Ropsten"),
                            ("4", "Rinkeby"),
                            ("56", "BNB Chain"),
                            ("43114", "Avalanche"),
                            ("137", "Polygon"),
                        ],
                        default="1",
                        max_length=12,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("ERC20", "Erc20"),
                            ("ERC721", "Erc721"),
                            ("ERC1155", "Erc1155"),
                        ],
                        default="ERC20",
                        max_length=12,
                    ),
                ),
                ("amount", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="event",
            name="limit_per_person",
        ),
        migrations.DeleteModel(
            name="BlockchainRequirements",
        ),
        migrations.AddField(
            model_name="ticketoption",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="root.event"
            ),
        ),
    ]
