# Generated by Django 4.2 on 2023-06-01 00:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0049_remove_checkoutsession_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
