# Generated by Django 4.0.7 on 2022-09-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0049_ticketoption_remove_event_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketoption",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticketoption",
            name="asset_address",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
