# Generated by Django 4.2 on 2023-06-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0058_remove_txfiat_stripe_line_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="txfiat",
            name="stripe_line_items",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
