# Generated by Django 4.2 on 2023-06-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0060_alter_event_fiat_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="txfiat",
            name="stripe_session_url",
            field=models.TextField(
                blank=True, default="", help_text="Stripe checkout session URL."
            ),
        ),
    ]
