# Generated by Django 4.2 on 2023-06-20 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("root", "0061_alter_txfiat_stripe_session_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "permissions": [
                    (
                        "manage_member_permissions",
                        "Can manage team members' permissions",
                    ),
                    (
                        "manage_payment_details",
                        "Can view, change and manage team payment details",
                    ),
                ]
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
