# Generated by Django 4.2 on 2023-06-20 02:21
from django.db import migrations
from apps.root.models import Membership

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Team = apps.get_model('root', 'Team')

    # Create Groups
    for i in Membership.GroupChoices:
        Group.objects.get_or_create(name=i)

    # Set Default Admins
    for team in Team.objects.all():
        first_user = team.membership_set.order_by("created").first()
        admin_group = Group.objects.get(name=Membership.GroupChoices.ADMIN)
        first_user.group = admin_group
        first_user.save()


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Team = apps.get_model('root', 'Team')

    # Remove Groups
    Group.objects.filter(
        name__in=Membership.GroupChoices
    ).delete()

    # Remove Default Admins
    for team in Team.objects.all():
        first_user = team.membership_set.order_by("created").first()
        first_user.group = None
        first_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0062_alter_team_options_membership_group"),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
