# Generated by Django 4.2 on 2023-06-26 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0063_alter_event_organizer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
    ]
