# Generated by Django 4.2 on 2023-06-20 03:00
from django.db import migrations
from apps.root.models import Membership

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # get perms
    permissions = Permission.objects.filter(
        codename__in=[
            "manage_member_permissions",
            "manage_payment_details"
        ]
    )

    # get group and set perms
    admin_group = Group.objects.get(name=Membership.GroupChoices.ADMIN)
    admin_group.permissions.set(permissions)


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # get perms
    Permission.objects.filter(
        codename__in=[
            "manage_member_permissions",
            "manage_payment_details"
        ]
    )

    # get group and remove perms
    admin_group = Group.objects.get(name=Membership.GroupChoices.ADMIN)
    admin_group.permissions.set([])

class Migration(migrations.Migration):
    dependencies = [
        ("root", "0063_default_groups_admins"),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
