# Generated by Django 4.2 on 2023-06-20 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0064_new_admin_perms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "permissions": [
                    (
                        "manage_members",
                        "Can add and remove team members as well as their group",
                    ),
                    (
                        "manage_payment_details",
                        "Can view, change and manage team payment details",
                    ),
                ]
            },
        ),
    ]
