# Generated by Django 4.2 on 2023-06-27 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0064_remove_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tierassetownership",
            name="balance_required",
            field=models.IntegerField(
                default=1,
                help_text="The number of NFTs are required to claim your ticket tier.",
            ),
        ),
        migrations.AlterField(
            model_name="tierassetownership",
            name="network",
            field=models.IntegerField(
                choices=[
                    (1, "Ethereum"),
                    (5, "Ethereum (Goerli TestNet)"),
                    (11155111, "Ethereum (Sepolia TestNet)"),
                    (80001, "Ethereum (Mumbai TestNet)"),
                    (137, "Polygon"),
                    (56, "Binance Smart Chain"),
                    (97, "Binance Smart Chain (TestNet)"),
                    (43114, "Avalanche"),
                    (43113, "Avalanche (TestNet)"),
                    (250, "Fantom"),
                    (25, "Cronos"),
                    (338, "Cronos (TestNet)"),
                    (42161, "Arbitrum"),
                ],
                default=1,
                help_text="Which blockchain is your NFT collection on?",
            ),
        ),
        migrations.AlterField(
            model_name="tierassetownership",
            name="token_address",
            field=models.CharField(
                default="",
                help_text="What is the contract address of your NFT collection?",
                max_length=42,
            ),
        ),
        migrations.AlterField(
            model_name="tierassetownership",
            name="token_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                help_text="Which specific token IDs of the NFT collection are required?",
                null=True,
                size=None,
            ),
        ),
    ]
