# Generated by Django 4.2 on 2023-08-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0073_whitelabel_alter_event_fiat_currency_team_whitelabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabel",
            name="font_bold",
            field=models.FileField(blank=True, null=True, upload_to="whitelabel__font"),
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="font_regular",
            field=models.FileField(blank=True, null=True, upload_to="whitelabel__font"),
        ),
    ]
