# Generated by Django 4.2 on 2023-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0075_whitelabel_ticket_logo_whitelabel_ticket_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whitelabel",
            name="ticket_logo",
            field=models.FileField(blank=True, null=True, upload_to="whitelabel__logo"),
        ),
    ]
