# Generated by Django 4.2 on 2023-08-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0076_alter_whitelabel_ticket_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabel",
            name="ticket_bg_color",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
