# Generated by Django 4.2 on 2023-08-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0077_whitelabel_ticket_bg_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelabel",
            name="ticket_text_color",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
