# Generated by Django 4.2 on 2023-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0078_whitelabel_ticket_text_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="whitelabel",
            old_name="ticket_logo_url",
            new_name="ticket_logo_google",
        ),
        migrations.AddField(
            model_name="whitelabel",
            name="ticket_logo_apple",
            field=models.ImageField(
                blank=True, null=True, upload_to="whitelabel__logo"
            ),
        ),
    ]
