# Generated by Django 4.2.6 on 2023-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0083_alter_event_fiat_currency_messagebatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="allow_messaging",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="allow_rsvp",
            field=models.BooleanField(default=False),
        ),
    ]
