# Generated by Django 4.2.6 on 2023-11-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0084_team_allow_messaging_team_allow_rsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvpbatch",
            name="failure_list",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rsvpbatch",
            name="success_list",
            field=models.TextField(blank=True),
        ),
    ]
