# Generated by Django 4.2.6 on 2023-11-06 06:52

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0086_team_slug_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="title"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                help_text="Brief name for your event. Must be unique!", max_length=255
            ),
        ),
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("team", "title")},
        ),
    ]
