# Generated by Django 4.2.6 on 2024-01-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0092_alter_tickettier_guest_supply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="tx_type",
            field=models.CharField(
                choices=[
                    ("FIAT", "Fiat"),
                    ("BLOCKCHAIN", "Blockchain"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                    ("FREE", "Free"),
                    ("RSVP", "RSVP"),
                ],
                default="FIAT",
                max_length=50,
            ),
        ),
    ]
