# Generated by Django 5.0.1 on 2024-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0097_tierfiat_price_per_ticket_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettier",
            name="tx_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIAT", "Fiat"),
                    ("BLOCKCHAIN", "Blockchain"),
                    ("ASSET_OWNERSHIP", "Asset Ownership"),
                    ("FREE", "Free"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
