# Generated by Django 5.0.1 on 2024-02-07 19:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0100_checkoutsession_skip_expiration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkoutsession",
            old_name="skip_expiration",
            new_name="skip_validation",
        ),
    ]
