# Generated by Django 5.0.2 on 2024-03-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0107_txassetownership_delegated_wallets_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="txassetownership",
            old_name="delegated_wallets",
            new_name="delegated_wallet",
        ),
    ]
