# Generated by Django 5.0.1 on 2024-02-27 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0108_alter_tickettier_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tickettier",
            options={"ordering": ("-modified",)},
        ),
        migrations.RemoveField(
            model_name="tickettier",
            name="is_archived",
        ),
    ]
