# Generated by Django 5.0.2 on 2024-03-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0109_rename_hidden_tickets_tickettier_hidden_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettier",
            name="hidden_availability",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not to hide the number of available tickets from the public.",
            ),
        ),
    ]
