# Generated by Django 5.0.2 on 2024-03-12 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0111_rename_hidden_tickettier_hidden_from_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tickettier",
            old_name="ticket_type",
            new_name="name",
        ),
    ]
