# Generated by Django 5.0.2 on 2024-03-13 00:28

from django.db import migrations

def copy_data_from_tier_asset_ownership(apps, schema_editor):
    TicketTier = apps.get_model('root', 'TicketTier')

    # Get and loop over all ticket tiers
    ticket_tiers = TicketTier.objects.all().select_related("tier_asset_ownership")
    for tier in ticket_tiers:
        # Check for tier_asset_ownership relation
        # If none, skip to next item in loop
        if not tier.tier_asset_ownership:
            continue

        # copy fields
        tier.blockchain = tier.tier_asset_ownership.blockchain
        tier.network = tier.tier_asset_ownership.network
        tier.asset_type = tier.tier_asset_ownership.asset_type
        tier.balance_required = tier.tier_asset_ownership.balance_required
        tier.token_address = tier.tier_asset_ownership.token_address
        tier.token_id = tier.tier_asset_ownership.token_id
        tier.deprecated_issued_token_id = tier.tier_asset_ownership.deprecated_issued_token_id

        # save tier
        tier.save()

def reverse_copy_data_from_tier_asset_ownership(apps, schema_editor):
    TicketTier = apps.get_model('root', 'TicketTier')

    # Set fields back to their default values
    TicketTier.objects.all().update(
        blockchain=TicketTier._meta.get_field('blockchain').get_default(),
        network=TicketTier._meta.get_field('network').get_default(),
        balance_required=TicketTier._meta.get_field('balance_required').get_default(),
        token_address=TicketTier._meta.get_field('token_address').get_default(),
        token_id=TicketTier._meta.get_field('token_id').get_default(),
        deprecated_issued_token_id=TicketTier._meta.get_field('deprecated_issued_token_id').get_default(),
    )

class Migration(migrations.Migration):

    dependencies = [
        ("root", "0115_tickettier_asset_type_tickettier_balance_required_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_data_from_tier_asset_ownership,
            reverse_code=reverse_copy_data_from_tier_asset_ownership
        )
    ]
