# Generated by Django 5.0.2 on 2024-03-13 02:27

from django.db import migrations

def copy_data_from_tier_fiat(apps, schema_editor):
    TicketTier = apps.get_model('root', 'TicketTier')

    # Get and loop over all ticket tiers
    ticket_tiers = TicketTier.objects.all().select_related("tier_fiat")
    for tier in ticket_tiers:
        # Check for fiat relation
        # If none, skip to next item in loop
        if not tier.tier_fiat:
            continue

        # copy fields
        tier.price_per_ticket = tier.tier_fiat.price_per_ticket
        tier.price_per_ticket_cents = tier.tier_fiat.price_per_ticket_cents

        # save tier
        tier.save()

def reverse_copy_data_from_tier_fiat(apps, schema_editor):
    TicketTier = apps.get_model('root', 'TicketTier')

    # Set fields back to their default values
    TicketTier.objects.all().update(
        price_per_ticket=TicketTier._meta.get_field('price_per_ticket').get_default(),
        price_per_ticket_cents=TicketTier._meta.get_field('price_per_ticket_cents').get_default()
    )

class Migration(migrations.Migration):
    dependencies = [
        ("root", "0117_tickettier_price_per_ticket_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_data_from_tier_fiat,
            reverse_code=reverse_copy_data_from_tier_fiat
        )
    ]
