# Generated by Django 5.0.2 on 2024-03-13 02:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0118_migrate_tier_fiat"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettier",
            name="deprecated_issued_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
