# Generated by Django 5.0.2 on 2024-03-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0124_remove_tickettier_tier_free_delete_tierfree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettier",
            name="tier_fiat",
        ),
        migrations.DeleteModel(
            name="TierFiat",
        ),
    ]
