# Generated by Django 5.0.2 on 2024-03-18 18:15

from django.db import migrations

def copy_data_from_tx_fiat(apps, schema_editor):
    CheckoutSession = apps.get_model('root', 'CheckoutSession')

    # Get and loop over all sessions
    sessions = CheckoutSession.objects.all().select_related("tx_fiat")
    for session in sessions:
        # Check for fiat relation
        # If none, skip to next item in loop
        if not session.tx_fiat:
            continue

        # copy fields
        session.stripe_session_id = session.tx_fiat.stripe_session_id
        session.stripe_session_url = session.tx_fiat.stripe_session_url
        session.stripe_line_items = session.tx_fiat.stripe_line_items

        # save session
        session.save()



class Migration(migrations.Migration):

    dependencies = [
        ("root", "0128_checkoutsession_stripe_line_items_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_data_from_tx_fiat,
            reverse_code=migrations.RunPython.noop
        )
    ]
