# Generated by Django 5.0.2 on 2024-03-18 19:06

from django.db import migrations

def copy_data_from_tx_asset_ownership(apps, schema_editor):
    CheckoutSession = apps.get_model('root', 'CheckoutSession')

    # Get and loop over all sessions
    sessions = CheckoutSession.objects.all().select_related("tx_asset_ownership")
    for session in sessions:
        # Check for fiat relation
        # If none, skip to next item in loop
        if not session.tx_asset_ownership:
            continue

        # copy fields
        session.wallet_address = session.tx_asset_ownership.wallet_address
        session.signed_message = session.tx_asset_ownership.signed_message
        session.is_wallet_address_verified = session.tx_asset_ownership.is_wallet_address_verified
        session.delegated_wallet = session.tx_asset_ownership.delegated_wallet
        session.redeemed_nfts = session.tx_asset_ownership.redeemed_nfts

        # save session
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0131_checkoutsession_delegated_wallet_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_data_from_tx_asset_ownership,
            reverse_code=migrations.RunPython.noop
        )
    ]
