# Generated by Django 5.0.2 on 2024-03-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0135_remove_checkoutsession_tx_free_delete_txfree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="tx_asset_ownership",
        ),
        migrations.DeleteModel(
            name="TxAssetOwnership",
        ),
    ]
