# Generated by Django 5.0.2 on 2024-03-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0140_migrate_waitlist_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkoutsession",
            name="is_waiting_list",
        ),
        migrations.RemoveField(
            model_name="checkoutsession",
            name="skip_validation",
        ),
    ]
