# Generated by Django 5.0.2 on 2024-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0141_remove_checkoutsession_is_waiting_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("VALID", "Valid"),
                    ("PROCESSING", "Processing"),
                    ("FAILED", "Failed"),
                    ("FULFILLED", "Fulfilled"),
                ],
                default="VALID",
                max_length=50,
            ),
        ),
    ]
