# Generated by Django 5.0.2 on 2024-03-19 19:07

from django.db import migrations

def migrate_order_status(apps, schema_editor):
    CheckoutSession = apps.get_model('root', 'CheckoutSession')

    # Get all ticket sessions
    sessions = CheckoutSession.objects.all()
    from apps.root.models import CheckoutSession
    for session in sessions:
        # update completed -> FULFILLED
        if session.order_status == "COMPLETED":
            session.order_status == CheckoutSession.OrderStatus.FULFILLED
            session.save()



class Migration(migrations.Migration):

    dependencies = [
        ("root", "0142_alter_checkoutsession_order_status"),
    ]

    operations = [
        migrations.RunPython(
            migrate_order_status,
            reverse_code=migrations.RunPython.noop
        )
    ]