# Generated by Django 5.0.2 on 2024-03-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0143_migrate_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="delegated_wallet",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="is_wallet_address_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="redeemed_nfts",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="signed_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="checkoutsession",
            name="wallet_address",
            field=models.CharField(blank=True, default="", max_length=42),
        ),
    ]
