# Generated by Django 5.0.2 on 2024-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0146_alter_checkoutsession_session_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutsession",
            name="waitlist_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WAITLIST_JOINED", "Waitlist joined"),
                    ("WAITLIST_APPROVED", "Waitlist approved"),
                    ("WAITLIST_REJECTED", "Waitlist rejected"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
