# Generated by Django 5.0.2 on 2024-03-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0153_remove_event_address_1_remove_event_address_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="theme",
        ),
    ]
