# Generated by Django 5.0.1 on 2024-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("root", "0163_remove_tickettier_price_per_ticket_cents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                default="We hope to see you there!",
                help_text="A short description of your event.",
            ),
        ),
    ]
