# Generated by Django 5.0.3 on 2024-04-09 16:12

from django.db import migrations

def migrate_rsvp_batch_array_field(apps, schema_editor):
    RSVPBatch = apps.get_model('root', 'RSVPBatch')

    # Get all RSVP Batches
    rsvp_batches = RSVPBatch.objects.all()
    for batch in rsvp_batches:
        # Convert success list into proper list
        if batch.success_list:
            batch.success_list = {email.strip() for email in batch.success_list.split(',') if email.strip()}
        else:
            batch.success_list = {}
        # Convert failure list into proper list
        if batch.failure_list:
            batch.failure_list = {email.strip() for email in batch.failure_list.split(',') if email.strip()}
        else:
            batch.failure_list = {}

        batch.save()
        print(batch.success_list)
        print(batch.failure_list)

class Migration(migrations.Migration):

    dependencies = [
        ('root', '0167_rename_waiting_queue_enabled_event_waitlist_enabled'),
    ]

    operations = [
        migrations.RunPython(
            migrate_rsvp_batch_array_field,
            reverse_code=migrations.RunPython.noop
        )
    ]