# Generated by Django 5.0.3 on 2024-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0170_migrate_rsvp_batch_strip_quotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
