# Generated by Django 3.2.11 on 2022-01-26 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('general_type', models.CharField(choices=[('AIRDROP', 'AIRDROP'), ('TICKET', 'TICKET')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokengates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirdropGate',
            fields=[
                ('tokengate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='root.tokengate')),
                ('chain', models.CharField(choices=[('ETHEREUM', 'ETHEREUM'), ('WAX', 'WAX')], max_length=50)),
                ('asset_type', models.CharField(choices=[('ERC20', 'ERC20'), ('ERC721', 'ERC721'), ('ERC1155', 'ERC1155')], max_length=50)),
                ('asset_address', models.CharField(max_length=400)),
                ('amount_per_person', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('root.tokengate',),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.CharField(choices=[('ETHEREUM', 'ETHEREUM'), ('WAX', 'WAX')], max_length=50)),
                ('asset_type', models.CharField(choices=[('ERC20', 'ERC20'), ('ERC721', 'ERC721'), ('ERC1155', 'ERC1155')], max_length=50)),
                ('asset_address', models.CharField(max_length=400)),
                ('amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('tokengate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='root.tokengate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirdropList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_address', models.CharField(max_length=400)),
                ('transaction_hash', models.CharField(max_length=400)),
                ('airdropgate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airdrop_lists', to='root.airdropgate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
