# Generated by Django 3.2.11 on 2022-01-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_airdropgate_airdroplist_requirement_tokengate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_code', models.CharField(max_length=400, unique=True)),
                ('signing_message', models.CharField(max_length=400)),
                ('wallet_address', models.CharField(max_length=400)),
                ('is_verified', models.BooleanField(default=False)),
                ('tokengate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='root.tokengate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
