# Generated by Django 3.2.11 on 2022-01-26 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketGate',
            fields=[
                ('tokengate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='root.tokengate')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=1024)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('root.tokengate',),
        ),
        migrations.CreateModel(
            name='TicketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_address', models.CharField(max_length=400)),
                ('ticket_url', models.URLField()),
                ('token_id', models.IntegerField()),
                ('ticketgate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_lists', to='root.ticketgate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
