# Generated by Django 3.2.11 on 2022-01-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_alter_airdropgate_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airdroplist',
            old_name='airdropgate',
            new_name='tokengate',
        ),
        migrations.RenameField(
            model_name='ticketlist',
            old_name='ticketgate',
            new_name='tokengate',
        ),
    ]
