name: Code Quality
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r config/requirements/local.txt
      - name: ruff quality checks
        working-directory: ./backend
        run: |
          ruff check .
          ruff format . --check
      - name: mypy quality checks
        working-directory: ./backend
        run: |
          mypy . --install-types --non-interactive --ignore-missing-imports
      - name: djhtml quality checks
        working-directory: ./backend
        run: |
          djhtml .