name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.5]

    steps:
    - name: Load .env file
      uses: xom9ikk/dotenv@v1.0.2
      with:
        path: backend/.envs/
        mode: test

    # Setup python
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install deps
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/config/requirements/test.txt

    # Run tests
    - name: Run Tests
      run: |
        python backend/manage.py test
