name: EventPortal CI
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install node_modules
      working-directory: frontend/eventportal
      run: npm install
    - name: Run TypeScript type checks
      working-directory: frontend/eventportal
      run: npm run lint
