name: Ruff
on: [push, pull_request]
jobs:
  ruff_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
    with:
      src: './backend'
  ruff_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
    with:
      args: 'format --check'
      src: './backend'