name: Push Master to Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Staging Branch
        run: |
          git checkout origin/staging
          git merge --ff-only origin/master
          git push origin staging
