name: Push Master to Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use version 4 of the checkout action
        with:
          ref: staging  # Specify the branch to checkout

      - name: Push to Staging Branch
        run: |
          git pull origin master  # Pull the latest changes from 'master'
          git push origin staging  # Push the changes to 'staging'
