name: Code Quality
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r config/requirements/local.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: django testing
        working-directory: ./backend
        run : |
          ./manage.py test --settings=config.settings.test --failfast
